@NeedToDo.APIs_HostAddress = http://localhost:5037
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJqdGkiOiIwNTM2MjliMy02ODg5LTQxNzEtOTRlMS1lYjExMWU4MzdjODgiLCJleHAiOjE3Nzc4MTIwMjcsImlzcyI6InlvdXItYXBwLWlzc3VlciIsImF1ZCI6InlvdXItYXBwLWF1ZGllbmNlIn0.tZ0Tn2xixbbjkhVu9hLEmOkbkAYNhIEOlf21FOiFyIc

### Login — returns a JWT token
POST {{NeedToDo.APIs_HostAddress}}/Auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "password"
}

###

### Get all ToDos (requires auth — set @token above)
GET {{NeedToDo.APIs_HostAddress}}/ToDo
Accept: application/json
Authorization: Bearer {{token}}

###

### Add a new ToDo (no auth required)
POST {{NeedToDo.APIs_HostAddress}}/ToDo
Content-Type: application/json
Accept: application/json

{
  "title": "Buy car"
}

###